# Generated by Django 6.0.5 on 2026-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("mbti", models.CharField(max_length=4)),
                ("pub_date", models.DateField(auto_now_add=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("is_HoF", models.BooleanField(default=False)),
                ("cheerup", models.PositiveIntegerField(default=0)),
                ("gonggam", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
