# Generated by Django 6.0.5 on 2026-06-17 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worry",
            name="later_answer",
            field=models.ManyToManyField(
                blank=True,
                related_name="worry_later_answer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
