# Generated by Django 6.0.5 on 2026-06-18 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0002_worry_later_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worry",
            name="cheerup_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="worry",
            name="gonggam_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="worry",
            name="cheerup",
        ),
        migrations.RemoveField(
            model_name="worry",
            name="gonggam",
        ),
        migrations.AddField(
            model_name="worry",
            name="cheerup",
            field=models.ManyToManyField(
                blank=True, related_name="worry_cheerup", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="worry",
            name="gonggam",
            field=models.ManyToManyField(
                blank=True, related_name="worry_gonggam", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
