# Generated by Django 6.0.5 on 2026-06-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0003_worry_cheerup_count_worry_gonggam_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worry",
            name="writer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation", models.TextField()),
                ("my_action", models.TextField()),
                ("recommendation", models.TextField()),
                ("pub_date", models.DateField(auto_now_add=True)),
                ("is_satisfied", models.BooleanField(default=False)),
                (
                    "worry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worries.worry"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
