# Generated by Django 6.0.5 on 2026-06-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_worries_to_fallback_user(apps, schema_editor):
    Worry = apps.get_model("worries", "Worry")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    fallback_user = User.objects.order_by("pk").first()
    if fallback_user is None:
        fallback_user = User.objects.create(
            username="migration_worry_writer",
            password="!",
        )

    Worry.objects.filter(writer__isnull=True).update(writer_id=fallback_user.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0003_worry_cheerup_count_worry_gonggam_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worry",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            assign_existing_worries_to_fallback_user,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="worry",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation", models.TextField()),
                ("my_action", models.TextField()),
                ("recommendation", models.TextField()),
                ("pub_date", models.DateField(auto_now_add=True)),
                ("is_satisfied", models.BooleanField(default=False)),
                (
                    "worry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worries.worry"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
