# Generated by Django 6.0.5 on 2026-06-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0004_worry_writer_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="hit",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
