# Generated by Django 6.0.5 on 2026-06-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0005_answer_hit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="is_satisfied",
            field=models.IntegerField(default=0),
        ),
    ]
