# Generated by Django 6.0.5 on 2026-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worries', '0005_answer_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_disliked',
            field=models.BooleanField(default=False),
        ),
    ]
