# Generated by Django 6.0.5 on 2026-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0007_alter_answer_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worry",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
