# Generated by Django 6.0.5 on 2026-06-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worries', '0008_alter_answer_id_alter_worry_id'),
        ('worries', '0008_alter_worry_pub_date'),
    ]

    operations = [
    ]
