# Generated by Django 6.0.5 on 2026-06-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worries', '0009_merge_20260624_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='worry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
