# Generated by Django 6.0.5 on 2026-06-17 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('mbti', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('point', models.IntegerField(default=0)),
                ('worry_count', models.IntegerField(default=0)),
                ('worry_yang', models.IntegerField(default=0)),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
