# Generated by Django 6.0.5 on 2026-05-31 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField()),
                ('job', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('mbti', models.CharField(max_length=4)),
                ('point', models.IntegerField(default=0)),
                ('worry_count', models.IntegerField(default=0)),
                ('worry_yang', models.IntegerField(default=0)),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
