# Generated by Django 6.0.5 on 2026-06-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_profile_birth_date_remove_profile_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="point",
            new_name="points",
        ),
        migrations.AddField(
            model_name="profile",
            name="attendance_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_attendance",
            field=models.DateField(blank=True, null=True),
        ),
    ]
