# Generated by Django 6.0.5 on 2026-06-22 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_rename_point_profile_points_profile_attendance_count_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="worry_yang",
        ),
        migrations.AddField(
            model_name="profile",
            name="current_yang",
            field=models.CharField(default="new_yang", max_length=50),
        ),
        migrations.CreateModel(
            name="UserYang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yang_id", models.CharField(max_length=50)),
                ("purchased_at", models.DateField(auto_now_add=True)),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="have_yangs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
