# Generated by Django 6.0.5 on 2026-06-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_profile_worry_yang_profile_current_yang_and_more"),
        ("accounts", "0008_alter_attendance_id_alter_profile_id"),
    ]

    operations = []
