# Generated by Django 6.0.5 on 2026-06-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_merge_20260624_0257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="points",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="profile",
            name="worry_count",
            field=models.IntegerField(default=5),
        ),
    ]
