# Generated by Django 6.0.5 on 2026-06-19 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("worries", "0004_worry_writer_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Epilogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ep_han_madi", models.CharField(max_length=50)),
                ("ep_title", models.CharField(max_length=50)),
                ("ep_content", models.TextField()),
                ("ep_pub_date", models.DateField(auto_now_add=True)),
                ("ep_is_delete", models.BooleanField(default=False)),
                (
                    "worry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worries.worry"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
