# Generated by Django 6.0.5 on 2026-06-20 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_epilogue_later_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='epilogue',
            name='ep_gonggam',
            field=models.ManyToManyField(blank=True, related_name='ep_gonggam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='epilogue',
            name='ep_gonggam_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
