# Generated by Django 6.0.5 on 2026-06-22 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writers", "0003_epilogue_ep_gonggam_epilogue_ep_gonggam_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="epilogue",
            name="visible_users",
            field=models.ManyToManyField(
                blank=True, related_name="visible_epilogue", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
