# Generated by Django 4.2.30 on 2026-06-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0005_pointlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epilogue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
