# Generated by Django 6.0.5 on 2026-06-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0006_alter_epilogue_id_alter_pointlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epilogue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
