# Generated by Django 6.0.5 on 2026-06-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worries", "0010_alter_answer_id_alter_worry_id"),
        ("writers", "0007_alter_epilogue_id_alter_pointlog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epilogue",
            name="worry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="worries.worry"
            ),
        ),
    ]
