# Generated by Django 6.0.5 on 2026-06-24 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writers", "0010_alter_epilogue_id_alter_pointlog_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="epilogue",
            name="popup_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="epilogue_popup_queue",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
